# Because the Gloo Edge Enterprise Helm chart uses the open source chart as a dependency, you must add the gloo. prefix to all open source Gloo Edge chart values.
# This applies to all values except for global.*. For example, when you install Gloo Edge Enterprise, gateway.certGenJob.enabled must be changed to gloo.gateway.certGenJob.enabled, but global.glooRbac.create remains unchanged.
# See chart values for more detail: https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/
gloo:
  discovery:
    enabled: false
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          replicas: 2
      gatewaySettings:
        options:
          accessLoggingService:
            accessLog:
            - fileSink:
                path: /dev/stdout
                stringFormat: ""
    gatewayProxyInternal:
      disabled: true
      kind:
        deployment:
          replicas: 2
      service:
        httpsFirst: true
        extraAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: private
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: private
        options:
          accessLoggingService:
            accessLog:
              - fileSink:
                  path: /dev/stdout
                  stringFormat: ""
  gloo:
    deployment:
      replicas: 2
  gateway:
    deployment:
      replicas: 2
  global:
    glooStats:
      enabled: true
      enableStatsRoute: true
      setDatadogAnnotations: true
  settings:
    invalidConfigPolicy:
      replaceInvalidRoutes: true
      invalidRouteResponseBody: "Gloo Gateway has invalid configuration. Administrators should run `glooctl check` to find and fix config errors."
      invalidRouteResponseCode: 404
    watchNamespaces: [] # All Namespaces
# Disable Gloo Fed but enable the legacy UI
gloo-fed:
  enabled: false
  create_license_secret: false
  glooFedApiserver:
    enable: false